version: "3.8"
services:
  openwakeword:
    restart: always
    image: "ghcr.io/litinoveweedle/wyoming-openwakeword:latest"
    ports:
      - "10400:10400"
    command:
      - "--uri"
      - "tcp://0.0.0.0:10400"
      - "--preload-model"
      - "hey_jarvis"
      - "--debug"
  satellite:
    restart: always
    image: "ghcr.io/litinoveweedle/wyoming-satellite:latest"
    ports:
      - "10700:10700"
    devices:
      - /dev/snd:/dev/snd
    group_add:
      - audio
    volumes:
      - /etc/asound.conf:/etc/asound.conf:ro
    depends_on:
      - openwakeword
    links:
      - openwakeword
    command:
      - "--name"
      - "bedroom"
      - "--uri"
      - "tcp://0.0.0.0:10700"
      - "--wake-uri"
      - "tcp://openwakeword:10400"
      - "--wake-word-name"
      - "hey_jarvis"
      - "--mic-command"
      - "/usr/bin/arecord -r 16000 -c 1 -f S16_LE -t raw -D mic"
      - "--snd-command"
      - "/usr/bin/aplay -r 22050 -c 1 -f S16_LE -t raw -D assistent"
      - "--awake-wav"
      - "sounds/awake.wav"
      - "--done-wav"
      - "sounds/done.wav"
      - "--debug"
