version: "3.8"
services:
  openwakeword:
    image: "ghcr.io/litinoveweedle/wyoming-openwakeword:latest"
    ports:
      - "10400:10400"
    command:
      - "--uri"
      - "tcp://0.0.0.0:10400"
      - "--preload-model"
      - "ok_nabu"
      - "--debug"
  satellite:
    image: "ghcr.io/litinoveweedle/wyoming-satellite:latest"
    ports:
      - "10700:10700"
    devices:
      - /dev/snd:/dev/snd
    group_add:
      - audio
    volumes:
      - /etc/asound.conf:/etc/asound.conf:ro
    command:
      - "--name"
      - "bedroom"
      - "--uri"
      - "tcp://0.0.0.0:10700"
      - "--wake-uri"
      - "tcp://openwakeword:10400"
      - "--wake-word-name"
      - "ok_nabu"
      - "--mic-command"
      - "/usr/bin/arecord -r 48000 -c 1 -f S16_LE -t raw -D mic"
      - "--snd-command"
      - "/usr/bin/aplay -r 44100 -c 1 -f S16_LE -t raw -D assistent"
      - "--debug"
