#!/usr/bin/env python3
import argparse
import subprocess
import venv
from pathlib import Path

_DIR = Path(__file__).parent
_PROGRAM_DIR = _DIR.parent
_VENV_DIR = _PROGRAM_DIR / ".venv"

parser = argparse.ArgumentParser()
parser.add_argument("--dev", action="store_true", help="Install dev requirements")
parser.add_argument("--vad", action="store_true", help="Install voice activity detection requirements")
parser.add_argument("--aen", action="store_true", help="Install audio enhacement requirements")
args = parser.parse_args()

# Create virtual environment
builder = venv.EnvBuilder(with_pip=True)
context = builder.ensure_directories(_VENV_DIR)
builder.create(_VENV_DIR)

# Upgrade dependencies
pip = [context.env_exe, "-m", "pip"]
subprocess.check_call(pip + ["install", "--upgrade", "pip"])
subprocess.check_call(pip + ["install", "--upgrade", "setuptools", "wheel"])

# Install requirements
subprocess.check_call(
    pip
    + [
        "install",
        "--extra-index-url",
        "https://www.piwheels.org/simple",
        "-f",
        "https://synesthesiam.github.io/prebuilt-apps/",
        "-r",
        str(_PROGRAM_DIR / "requirements.txt"),
    ]
)

if args.vad:
    # Install dev requirements
    subprocess.check_call(
        pip + ["install", "-r", str(_PROGRAM_DIR / "requirements_vad.txt")]
    )

if args.aen:
    # Install dev requirements
    subprocess.check_call(
        pip + ["install", "-r", str(_PROGRAM_DIR / "requirements_audio_enhancement.txt")]
    )

if args.dev:
    # Install dev requirements
    subprocess.check_call(
        pip + ["install", "-r", str(_PROGRAM_DIR / "requirements_dev.txt")]
    )

